### ISSUE TITLE
与QMUI一起使用,会导致UITextfiled点击闪退

### ISSUE THREAD

**Issue by 19aneng** [ECPay/ECPayPaymentGatewayKit_iOS#1]
与QMUI一起使用,会导致UITextfiled点击闪退(必现)

重现步骤
项目集成ECPayPaymentGatewayKit_iOS和QMUI_iOS.
相关链接
1.[ECPayPaymentGatewayKit_iOS](https://github.com/ECPay/ECPayPaymentGatewayKit_iOS)
2.https://github.com/Tencent/QMUI_iOS

具体原因分析
应该是拦截闪退那里有问题导致
https://www.jianshu.com/p/fcf10656dcdd

**Comment by yen064** [comment]
We've figured it out the root cause, it's thirdparty pod for 'IQKeyboardManager'.
Please remove pod IQKeyboardManager(objective-c version), and add IQKeyboardManager for swift version might solve this problem, thanks and apologize for any inconvenience caused.

Example in Podfile:

<strike>pod 'IQKeyboardManager'</strike>
pod 'IQKeyboardManagerSwift'
